[env:xiaowa-esp32s3]
extends = esp32s3_base
board = esp32-s3-supermini
board_level = extra

upload_protocol = esptool
upload_speed = 921600

lib_deps =
  ${esp32s3_base.lib_deps}
  adafruit/Adafruit NeoPixel@1.15.2

build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32s3/diy/xiaowa-esp32s3